import type { Metadata } from 'next';
import Container from 'react-bootstrap/Container';
import Index from './pages/index';
import BeSignupForm from '@/global-components/signup-from';

export const metadata: Metadata = {
    title: 'Book Eilen',
    description: 'Generated by create next app',
};

export default function Home({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <Container>
                <div className="">
                    {/* <Index /> */}
                    <BeSignupForm />
                </div>
            </Container>
        </div>
    );
}
