import './globals.css';
import type { Metadata } from 'next';
import Container from 'react-bootstrap/Container';
import Index from './pages/index';

export const metadata: Metadata = {
    title: 'Book Eilen',
    description: 'Generated by create next app',
};

export default function Home({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <h1>hello afeef</h1>
            <Container>
                <div style={{ width: 500 }} className="mx-auto p-3 rounded ">
                    <Index />
                </div>
            </Container>
        </div>
    );
}
